name: Docker CI

on:
  push:
    branches: [ main ] # Ändere dies, wenn du einen anderen Branch verwendest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.1-rootless

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile # Passe dies an, falls dein Dockerfile woanders liegt
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dein-image:${{ github.sha }}

      - name: SSH and deploy to VPS
        uses: appleboy/ghaction-ssh@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/dein-image:${{ github.sha }}
            docker-compose up -d