version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "4321"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3001"
    tty: true
    depends_on:
      - datenbank
    env_file:
      - ./backend/.env

  datenbank:
    container_name: datenbank
    build:
      context: database
      dockerfile: Dockerfile
    expose:
      - "3306"
    env_file:
        - database/.env

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend

  certbot:
    container_name: certbot
    build:
      context: ./cert
      dockerfile: Dockerfile
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /check-cert.sh
    depends_on:
      - nginx