version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - datenbank
    environment:
      - MYSQL_HOST=datenbank
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=taskronaut

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  datenbank:
    build: ./datenbank
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=taskronaut