version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "4321"
    ports:
      - "4321:4321"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3001"
    ports:
      - "3001:3001"
    tty: true
    depends_on:
      - datenbank
    environment:
      - MYSQL_HOST=datenbank
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=TaskRonaut

  datenbank:
    build:
      context: ./datenbank
      dockerfile: Dockerfile
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=TaskRonaut
    volumes:
      - mysql_data:/var/lib/mysql  # Persistente Speicherung der Datenbank

  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS für verschlüsselten Zugriff
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/taskronaut.at:/etc/letsencrypt/live/taskronaut.at:ro  # Ganzes Verzeichnis einbinden
    depends_on:
      - frontend

volumes:
  mysql_data:  # Persistent Storage für MySQL
