version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "4321"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3001"
    tty: true
    depends_on:
      - datenbank
    environment:
      - MYSQL_HOST=datenbank
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=TaskRonaut

  datenbank:
    container_name: datenbank
    build:
      context: ./datenbank
      dockerfile: Dockerfile
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=TaskRonaut

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend

  certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      command: certonly --webroot -w /var/www/certbot --force-renewal --email paul.schreiber@it.htl-hl.ac.at -d taskronaut.at --agree-tos

  mailserver:
    container_name: mailserver
    image: tvial/docker-mailserver:latest
    hostname: taskronaut.at
    domainname: taskronaut.at
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./mail-data/config:/tmp/docker-mailserver/config:ro
      - ./mail-data/data:/var/mail
      - ./emailconf/postfix-accounts.cf:/tmp/docker-mailserver/postfix-accounts.cf:ro
      - ./emailconf/saslauthd.conf:/etc/default/saslauthd:ro
    environment:
      - ENABLE_TLS=0
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ONE_DIR=1
      - ENABLE_POSTGREY=1
      - MAILNAME=taskronaut.at
      - OVERRIDE_QUOTA=524288000
      - PERMIT_DOCKER=1
      - ENABLE_SASLAUTH=1
      - SASL_TYPE=dovecot
      - DOVECOT_PASSWORDS=yes
      - MAIL_USER=noreply@taskronaut.at
      - MAIL_PASS=MeinSehrStarkesPasswort