name: Deploy to VPS

on:
  push:
    branches:
      - main 
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: |
          cd backend/
          npm install

      - name: Run Jest tests
        run: |
          cd backend/
          npm test 

      - name: SSH into VPS and deploy
        if: success()
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd /root/taskronaut/
            chmod +x updateServer.sh
            sh updateServer.sh
         